// =====================
// LANGUAGE SYSTEM
// =====================

const TRANSLATIONS = {
  en: {
    // NAV
    navHome: "Home",
    navSubjects: "Subjects",
    navModes: "Modes",
    navContact: "Contact",
    navCta: "Start Test →",

    // HERO
    heroBadge: "Now with Competition Mode",
    heroTitle1: "Test your",
    heroTitle2: "knowledge.",
    heroTitle3: "Beat the clock.",
    heroDesc: "Challenge yourself across subjects. Compete against the timer. Track your score. Built for students who want to actually prepare — not just feel like they are.",
    heroBtn1: "Start a Test →",
    heroBtn2: "View Modes",
    heroStat1: "Subjects",
    heroStat2: "Per Question",
    heroStat3: "Free",
    heroStat4: "Always",
    heroPanelLabel: "Arena Pulse",
    heroPanelChip: "Live sync",
    heroPanelActive: "active today",
    heroPanelAccuracy: "24h average",
    heroPanelRuns: "all-time runs",
    heroPanelLanguages: "bilingual",
    heroPanelLanguagesValue: "EN / UZ",
    heroRoutePracticeLabel: "Practice Run",
    heroRoutePracticeTitle: "Build your streak",
    heroRoutePracticeCopy: "Pick a subject, move at your pace, and keep every result.",
    heroRoutePracticeAction: "Open practice →",
    heroRouteCompeteLabel: "Competition",
    heroRouteCompeteTitle: "Chase the board",
    heroRouteCompeteCopy: "10 seconds per question, ranked scores, and pure speed pressure.",
    heroRouteCompeteAction: "Open competition →",

    // LIVE STATS
    liveStatus: "System Snapshot",
    liveTitle: "See the board. Know the rules.",
    liveDesc: "Clear scopes for the numbers, a ranked competition board, and a direct path into play.",
    liveTotalQuizzes: "Total quizzes taken",
    liveTotalScope: "All-time",
    liveAverageScore: "Average score",
    liveAverageScope: "Last 24h",
    liveActiveUsers: "Active users",
    liveActiveScope: "Today",
    liveBoardLabel: "Competition Leaderboard",
    liveBoardTitle: "Who's #1 right now?",
    liveBoardDesc: "1,000 points per correct answer in Speed Mode. Ranked by total points across completed runs.",
    liveBoardBadge: "Top 5",
    liveRuns: "completed runs",
    livePoints: "points",
    livePrimaryCta: "Join Leaderboard →",
    liveSecondaryCta: "Start Practice",

    // SUBJECTS SECTION
    subjectsLabel: "Subjects",
    subjectsTitle: "Pick your subject.\nStart immediately.",
    subjectQuestions: "10 questions",

    // SUBJECT NAMES
    subjectMath: "Mathematics",
    subjectMathDesc: "Numbers, structures, logic. From arithmetic to algebra — test your calculation speed.",
    subjectEnglish: "English",
    subjectEnglishDesc: "Grammar, vocabulary, comprehension. Strengthen your language foundation.",
    subjectScience: "Natural Science",
    subjectScienceDesc: "Biology, chemistry, physics fundamentals. Explore the natural world through questions.",
    subjectHistory: "History",
    subjectHistoryDesc: "Key events, dates, figures. How well do you actually know the past?",
    subjectGeo: "Geography",
    subjectGeoDesc: "Countries, capitals, physical features. Test your knowledge of the world.",
    subjectCS: "Computer Science",
    subjectCSDesc: "Algorithms, logic, fundamentals. For the next generation of developers.",

    // MODES SECTION
    modesLabel: "Game Modes",
    modesTitle: "Two ways to play.",
    classicTag: "Classic",
    classicTitle: "Practice Mode",
    classicDesc: "No timer pressure. Work through questions at your own pace. See correct answers immediately. Best for learning and revision.",
    classicBtn: "Start Practice →",
    compTag: "Competition",
    compTitle: "Speed Mode",
    compDesc: "10 seconds per question. Points for correct answers. Score as high as you can before time runs out.",
    compBtn: "Compete Now →",

    // CONTACT
    contactLabel: "Contact",
    contactTitle: "Get in touch.",
    contactDesc: "Found a bug? Have a subject suggestion? Want to contribute questions? Reach out directly.",
    contactName: "First Name",
    contactSurname: "Last Name",
    contactEmail: "Email",
    contactMessage: "Message",
    contactSend: "Send Message",
    contactSent: "Sent ✓",

    // QUIZ PAGE
    selectSubject: "Choose a subject.",
    selectSubjectSub: "Pick a topic and start immediately.",
    subjectBadgeDefault: "Select Subject",
    questionOf: "Question",
    of: "of",
    scoreLabel: "Score:",
    nextBtn: "Next Question →",
    seeResults: "See Results →",
    tryAgain: "Try Again",
    backHome: "Back to Home",
    youGot: "You got",
    correct: "% correct",

    // GRADES
    gradeExcellent: "🔥 Excellent",
    gradeGood: "✅ Good",
    gradeAverage: "⚠️ Average",
    gradeStudy: "💀 Study more",

    // COMPETITION PAGE
    compPageTitle: "Speed Mode",
    compPageTitle1: "Speed",
    compPageTitle2: "Mode",
    compDescLobby: "10 seconds per question. Answer fast. Answer right. Your score is your rank.",
    compRule1: "Correct answer: +1000 points",
    compRule1Label: "Correct answer:",
    compRule1Value: "+1000 points",
    compRule2: "Wrong answer: 0 points",
    compRule2Label: "Wrong answer:",
    compRule2Value: "0 points",
    compRule3: "Time runs out: auto-counted as wrong",
    compRule4: "10 questions, all subjects mixed",
    startComp: "Start Competition →",
    pointsEarned: "points earned",
    correctLabel: "Correct",
    wrongLabel: "Wrong",
    timedOut: "Timed Out",
    playAgain: "Play Again",

    // HOW IT WORKS
    howLabel: "How it works",
    howTitle: "Three steps.\nThat's it.",
    howTitle1: "Three steps.",
    howTitle2: "That's it.",
    howStep1Title: "Choose a subject",
    howStep1Desc: "Pick from Mathematics, Science, History, Geography, English, or Computer Science.",
    howStep2Title: "Answer questions",
    howStep2Desc: "Practice at your own pace or race the clock in Competition mode. 10 questions per session.",
    howStep3Title: "Get your score",
    howStep3Desc: "See your result instantly. Know exactly what you got right and where you need work.",

    // PREVIEW
    previewLabel: "Try it now",
    previewTitle: "See how it feels.",
    previewTag: "💡 Sample Question — Computer Science",
    previewQ: "What is the time complexity of binary search?",
    previewCorrectFeedback: "✓ Correct! Binary search halves the search space each step → O(log n)",
    previewWrongFeedback: "✗ Not quite. The answer is D — O(log n).",
    previewCtaText: "Want the full experience?",
    previewCtaBtn: "Start a Real Quiz →",

    backBtn: "← Back",
    backHome: "Back to Home",
    compMode: "⚡ Competition",

    // COMP GRADES
    gradeUnstoppable: "🔥 Unstoppable",
    gradeStrong: "💪 Strong",
    gradeDecent: "⚠️ Decent",
    gradeTrain: "💀 Train harder",

    // SUBJECT BADGE NAMES
    badgeMath: "Mathematics",
    badgeEnglish: "English",
    badgeScience: "Natural Science",
    badgeHistory: "History",
    badgeGeo: "Geography",
    badgeCS: "Computer Science",
    subjectsTitle1: "Pick your subject.",
    subjectsTitle2: "Start immediately.",
    mixedSubject: "Mixed",
    liveEmpty: "No competition scores yet. Be the first to set the pace.",
    navLogin: "Log In",
    navRegister: "Register",
    navProfile: "Profile",
    navSettings: "Settings",
    navAdmin: "Admin",
    navLogout: "Log Out",
    dashboardOverview: "Overview",
    settingsTitle: "Account Settings",
    settingsOverviewTitle: "Account overview",
    settingsAccountHint: "Update your public profile details and avatar here.",
    settingsUsernameLabel: "Username",
    settingsEmailHint: "Email changes are not available yet.",
    settingsAvatarLabel: "Profile picture",
    settingsChangeAvatarHint: "Optional. Upload an image to update your avatar.",
    settingsSaveButton: "Save changes",
    settingsBackToProfile: "Back to Profile",
    settingsSaving: "Saving...",
    settingsSaved: "Settings updated ✓",
    settingsSaveFailed: "Could not save your changes.",
    settingsPreferencesTitle: "Preferences",
    settingsPreferencesHint: "Language updates instantly and stays saved on this browser.",
    settingsLanguageLabel: "Language",
    settingsLanguageEnglish: "English",
    settingsLanguageUzbek: "O'zbek",
    settingsLanguageHint: "We moved language controls here to keep the navbar cleaner on smaller screens.",
    settingsLanguageSaved: "Language updated ✓",
    settingsAccessLabel: "Access",
    settingsRoleAdmin: "Admin access",
    settingsRoleMember: "Member access",
    settingsUsernameTooShort: "Username must be at least 3 characters.",
    settingsImageReadFailed: "Failed to read selected image.",
    settingsDangerTitle: "Danger zone",
    settingsDangerHint: "Deleting your account permanently removes your profile, scores, and progress history.",
    settingsDeleteButton: "Delete account",
    settingsDeleting: "Deleting...",
    settingsDeleteConfirm: "Delete your account permanently? This cannot be undone.",
    settingsDeleteFailed: "Could not delete your account.",
    quizAuthTitle: "Log in to start a real quiz.",
    quizAuthDesc: "Your account is required so your scores and leaderboard progress can be saved.",
    quizAuthLogin: "Log In",
    quizAuthRegister: "Create Account",
    competitionAuthTitle: "Log in to compete for real.",
    competitionAuthDesc: "Competition mode saves your score to the leaderboard, so you need an account before starting.",
    quizLoading: "Loading questions...",
    quizNoQuestions: "No questions are available for this subject yet.",
    scoreSaving: "Saving your score...",
    scoreSaved: "Score saved successfully.",
    scoreSaveFailed: "Could not save your score.",
    scoreSaveLogin: "Log in again to save future scores.",
    loginTitle: "Welcome back.",
    loginDesc: "Log in to save quiz scores, compete on the leaderboard, and track your progress.",
    registerTitle: "Create your account.",
    registerDesc: "Register once, then keep your quiz history, best scores, and competition results in one place.",
    authEmailLabel: "Email",
    authPasswordLabel: "Password",
    authUsernameLabel: "Username",
    loginSubmit: "Log In",
    registerSubmit: "Create Account",
    authProcessing: "Processing...",
    loginSwitchText: "Need an account?",
    loginSwitchLink: "Register",
    registerSwitchText: "Already have an account?",
    registerSwitchLink: "Log in",
    profileMemberSince: "Member since",
    profileStartQuiz: "Start Practice",
    profileTotalQuizzes: "Total quizzes taken",
    profilePerformanceTab: "Performance",
    profileBestResult: "Best result",
    profileBadgesUnlocked: "Badges unlocked",
    profileFavoriteMode: "Favorite mode",
    profileTrendTitle: "Score trend",
    profileSubjectFocus: "Subject focus",
    profileActivityTitle: "Weekly activity",
    profileBestScores: "Best score per subject",
    profileRecentBadges: "Recent badges earned",
    profileHistory: "Score history",
    profileNoScores: "No scores yet. Finish a quiz to start building your history.",
    profileNoBadges: "No badges yet. Complete quizzes to start unlocking them.",
    profileSubjectHeader: "Subject",
    profileModeHeader: "Mode",
    profileScoreHeader: "Score",
    profileDateHeader: "Completed",
    profileLevelNewcomer: "Newcomer",
    profileLevelBeginner: "Beginner",
    profileLevelIntermediate: "Intermediate",
    profileLevelPro: "Pro",
    profileLevelExpert: "Expert",
    profileLevelMaster: "Master",
    profileProgressToNextSingular: "{remaining} more quiz to reach {level}.",
    profileProgressToNextPlural: "{remaining} more quizzes to reach {level}.",
    profileProgressMax: "You are at the top level — keep it going!",
    profileTopSubjectEmpty: "No best score yet",
    profileTopSubjectValue: "Top: {subject} {score}",
    profileTrendSummary: "Last {count} runs, {average}% average.",
    profileTrendBadge: "{value}% avg",
    profileActivitySummary: "Active on {count} of the last 7 days.",
    profileFavoriteModeRuns: "{count} runs logged",
    profileRunsLabel: "Runs",
    profileBadgeEarnedOn: "Earned on {date}",
    modePractice: "Practice",
    modeCompetition: "Competition",
    badgeFirstQuiz: "First Strike",
    badgeFirstQuizDesc: "Completed your first QuizArena run.",
    badgePracticeStarter: "Practice Starter",
    badgePracticeStarterDesc: "Finished your first practice session.",
    badgeSpeedRunner: "Speed Runner",
    badgeSpeedRunnerDesc: "Jumped into competition mode for the first time.",
    badgeHighScorer: "High Scorer",
    badgeHighScorerDesc: "Scored 8 or more in a practice quiz.",
    badgePerfectTen: "Perfect Ten",
    badgePerfectTenDesc: "Earned a full 10/10 in practice mode.",
    badgeSpeedChampion: "Speed Champion",
    badgeSpeedChampionDesc: "Hit 8,000 or more points in competition mode.",
    badgeAllRounder: "All-Rounder",
    badgeAllRounderDesc: "Played practice quizzes across three different subjects.",
    badgeVeteran: "Veteran",
    badgeVeteranDesc: "Completed 10 total quizzes.",
    adminTitle: "Question and user management.",
    adminDesc: "Add bilingual questions, remove outdated ones, and monitor user activity from one panel.",
    adminTotalUsers: "Total users",
    adminQuestionsLive: "Questions live",
    adminQuizRunsCount: "Quiz runs",
    adminSubjectsLive: "Subjects live",
    adminGrowthTitle: "User growth",
    adminAddQuestion: "Add question",
    adminSubjectLabel: "Subject",
    adminQuestionEn: "Question text (EN)",
    adminQuestionUz: "Question text (UZ)",
    adminOptionsEn: "Options (EN)",
    adminOptionsUz: "Options (UZ)",
    adminCorrectOption: "Correct answer",
    adminSaveQuestion: "Save Question",
    adminQuestionBank: "Question bank",
    adminQuestionEnShort: "EN",
    adminQuestionUzShort: "UZ",
    adminActions: "Actions",
    adminSystemPulse: "System pulse",
    adminQuestionMix: "Question mix",
    adminQuestionMixDesc: "See how your content is distributed across subjects.",
    adminQuestionsShort: "Questions",
    adminGrowthSummaryValue: "{count} total members tracked.",
    adminGrowthBadge: "+{count} this month",
    adminPowerUsers: "Most active users",
    adminPowerUsersSummaryValue: "Showing {count} users with recorded activity.",
    adminPowerUsersMeta: "Best score {best}",
    adminRecentSignups: "Recent signups",
    adminUsersTitle: "Users",
    adminUserHeader: "User",
    adminTotalQuizzes: "Quizzes",
    adminBestScore: "Best score",
    adminRemoveQuestion: "Remove",
    adminSaved: "Question saved successfully.",
    adminNoQuestions: "No questions yet.",
    adminNoUsers: "No users yet.",
    adminNoRecentUsers: "No recent users yet.",
    adminLatestSignup: "Latest: {name}",
    adminAcrossSubjects: "Across {count} subjects",
    adminTopSubjectValue: "Top: {subject}",
    adminRunsTracked: "Tracked scores",
  },

  uz: {
    // NAV
    navHome: "Bosh sahifa",
    navSubjects: "Fanlar",
    navModes: "Rejimlar",
    navContact: "Aloqa",
    navCta: "Testni boshlash →",

    // HERO
    heroBadge: "Musobaqa rejimi mavjud",
    heroTitle1: "Bilimingizni",
    heroTitle2: "sinab ko'ring.",
    heroTitle3: "Vaqtdan ustun bo'ling.",
    heroDesc: "Fanlar bo'yicha o'zingizni sinab ko'ring. Taymer bilan raqobatlashing. Natijangizni kuzating. Haqiqatan tayyorlanmoqchi bo'lgan talabalar uchun.",
    heroBtn1: "Testni boshlash →",
    heroBtn2: "Rejimlarni ko'rish",
    heroStat1: "Fan",
    heroStat2: "Har savol",
    heroStat3: "Bepul",
    heroStat4: "Har doim",
    heroPanelLabel: "Arena holati",
    heroPanelChip: "Jonli sinxron",
    heroPanelActive: "bugun faol",
    heroPanelAccuracy: "24 soat o'rtacha",
    heroPanelRuns: "jami urinish",
    heroPanelLanguages: "ikki tilda",
    heroPanelLanguagesValue: "EN / UZ",
    heroRoutePracticeLabel: "Mashq sessiyasi",
    heroRoutePracticeTitle: "Seriyani boshlang",
    heroRoutePracticeCopy: "Fanni tanlang, o'z sur'atingizda ishlang va barcha natijalarni saqlang.",
    heroRoutePracticeAction: "Mashqni ochish →",
    heroRouteCompeteLabel: "Musobaqa",
    heroRouteCompeteTitle: "Reytingga hujum qiling",
    heroRouteCompeteCopy: "Har savolga 10 soniya, reytingli natijalar va sof tezlik bosimi.",
    heroRouteCompeteAction: "Musobaqani ochish →",

    // LIVE STATS
    liveStatus: "Tizim ko'rinishi",
    liveTitle: "Reytingni ko'ring. Qoidani biling.",
    liveDesc: "Raqamlar uchun aniq scope, musobaqa reytingi va o'yinga darhol kirish yo'li.",
    liveTotalQuizzes: "Yechilgan testlar",
    liveTotalScope: "Umumiy",
    liveAverageScore: "O'rtacha natija",
    liveAverageScope: "So'nggi 24 soat",
    liveActiveUsers: "Faol foydalanuvchilar",
    liveActiveScope: "Bugun",
    liveBoardLabel: "Musobaqa reytingi",
    liveBoardTitle: "Hozir #1 kim?",
    liveBoardDesc: "Tezlik rejimida har bir to'g'ri javob uchun 1 000 ball. Reyting yakunlangan urinishlardagi jami ball bo'yicha tuziladi.",
    liveBoardBadge: "Top 5",
    liveRuns: "yakunlangan urinish",
    livePoints: "ball",
    livePrimaryCta: "Reytingga qo'shiling →",
    liveSecondaryCta: "Mashqni boshlash",

    // SUBJECTS SECTION
    subjectsLabel: "Fanlar",
    subjectsTitle: "Fanni tanlang.\nHoziroq boshlang.",
    subjectQuestions: "10 ta savol",

    // SUBJECT NAMES
    subjectMath: "Matematika",
    subjectMathDesc: "Sonlar, tuzilmalar, mantiq. Arifmetikadan algebragacha — hisoblash tezligingizni sinang.",
    subjectEnglish: "Ingliz tili",
    subjectEnglishDesc: "Grammatika, lug'at, tushunish. Til poydevorini mustahkamlang.",
    subjectScience: "Tabiiy fanlar",
    subjectScienceDesc: "Biologiya, kimyo, fizika asoslari. Savollar orqali tabiat olamini o'rganing.",
    subjectHistory: "Tarix",
    subjectHistoryDesc: "Muhim voqealar, sanalar, shaxslar. O'tmishni qanchalik bilasiz?",
    subjectGeo: "Geografiya",
    subjectGeoDesc: "Mamlakatlar, poytaxtlar, geografik xususiyatlar. Dunyo haqidagi bilimingizni sinang.",
    subjectCS: "Informatika",
    subjectCSDesc: "Algoritmlar, mantiq, asoslar. Kelajak dasturchilari uchun.",

    // MODES SECTION
    modesLabel: "O'yin rejimlari",
    modesTitle: "Ikki xil o'yin.",
    classicTag: "Klassik",
    classicTitle: "Mashq rejimi",
    classicDesc: "Taymer bosimi yo'q. Savollar bo'ylab o'z sur'atingizda o'ting. To'g'ri javoblarni darhol ko'ring. O'rganish uchun eng yaxshi.",
    classicBtn: "Mashqni boshlash →",
    compTag: "Musobaqa",
    compTitle: "Tezlik rejimi",
    compDesc: "Har savolga 10 soniya. To'g'ri javoblar uchun ball. Vaqt tugagunicha imkon qadar yuqori ball to'plang.",
    compBtn: "Musobaqaga kirish →",

    // CONTACT
    contactLabel: "Aloqa",
    contactTitle: "Bog'laning.",
    contactDesc: "Xato topdingizmi? Fan taklif qilmoqchimisiz? Savol qo'shmoqchimisiz? To'g'ridan-to'g'ri murojaat qiling.",
    contactName: "Ism",
    contactSurname: "Familiya",
    contactEmail: "Email",
    contactMessage: "Xabar",
    contactSend: "Xabar yuborish",
    contactSent: "Yuborildi ✓",

    // QUIZ PAGE
    selectSubject: "Fan tanlang.",
    selectSubjectSub: "Mavzuni tanlang va hoziroq boshlang.",
    subjectBadgeDefault: "Fan tanlang",
    questionOf: "Savol",
    of: "/",
    scoreLabel: "Ball:",
    nextBtn: "Keyingi savol →",
    seeResults: "Natijalarni ko'rish →",
    tryAgain: "Qayta urinish",
    backHome: "Bosh sahifaga",
    youGot: "Siz",
    correct: "% to'g'ri javob berdingiz",

    // GRADES
    gradeExcellent: "🔥 A'lo",
    gradeGood: "✅ Yaxshi",
    gradeAverage: "⚠️ O'rtacha",
    gradeStudy: "💀 Ko'proq o'qing",

    // COMPETITION PAGE
    compPageTitle: "Tezlik rejimi",
    compPageTitle1: "Tezlik",
    compPageTitle2: "rejimi",
    compDescLobby: "Har savolga 10 soniya. Tez javob bering. To'g'ri javob bering. Natijangiz sizning reytingingiz.",
    compRule1: "To'g'ri javob: +1000 ball",
    compRule1Label: "To'g'ri javob:",
    compRule1Value: "+1000 ball",
    compRule2: "Noto'g'ri javob: 0 ball",
    compRule2Label: "Noto'g'ri javob:",
    compRule2Value: "0 ball",
    compRule3: "Vaqt tugasa: noto'g'ri hisoblanadi",
    compRule4: "10 ta savol, barcha fanlardan aralash",
    startComp: "Musobaqani boshlash →",
    pointsEarned: "ball to'plandi",
    correctLabel: "To'g'ri",
    wrongLabel: "Noto'g'ri",
    timedOut: "Vaqt tugadi",
    playAgain: "Qayta o'ynash",

    // HOW IT WORKS
    howLabel: "Qanday ishlaydi",
    howTitle: "Uch qadam.\nXolos.",
    howTitle1: "Uch qadam.",
    howTitle2: "Xolos.",
    howStep1Title: "Fan tanlang",
    howStep1Desc: "Matematika, Fan, Tarix, Geografiya, Ingliz tili yoki Informatikadan tanlang.",
    howStep2Title: "Savollarga javob bering",
    howStep2Desc: "O'z sur'atingizda mashq qiling yoki Musobaqa rejimida vaqt bilan raqobatlashing.",
    howStep3Title: "Natijangizni ko'ring",
    howStep3Desc: "Natijangizni darhol ko'ring. Nima to'g'ri, nimani o'rganish kerakligini bilib oling.",

    // PREVIEW
    previewLabel: "Hozir sinab ko'ring",
    previewTitle: "Qanday his ekanini ko'ring.",
    previewTag: "💡 Namuna savol — Informatika",
    previewQ: "Ikkilik qidiruvning vaqt murakkabligi qancha?",
    previewCorrectFeedback: "✓ To'g'ri! Ikkilik qidiruv har qadamda qidiruv maydonini ikki baravar qisqartiradi → O(log n)",
    previewWrongFeedback: "✗ Unchalik emas. To'g'ri javob D — O(log n).",
    previewCtaText: "To'liq tajriba xohlaysizmi?",
    previewCtaBtn: "Haqiqiy testni boshlash →",

    backBtn: "← Orqaga",
    compMode: "⚡ Musobaqa",

    // COMP GRADES
    gradeUnstoppable: "🔥 To'xtatib bo'lmas",
    gradeStrong: "💪 Kuchli",
    gradeDecent: "⚠️ O'rtacha",
    gradeTrain: "💀 Ko'proq mashq qiling",

    // SUBJECT BADGE NAMES
    badgeMath: "Matematika",
    badgeEnglish: "Ingliz tili",
    badgeScience: "Tabiat fanlari",
    badgeHistory: "Tarix",
    badgeGeo: "Geografiya",
    badgeCS: "Informatika",
    subjectsTitle1: "Fanni tanlang.",
    subjectsTitle2: "Hoziroq boshlang.",
    mixedSubject: "Aralash",
    liveEmpty: "Hali musobaqa natijalari yo'q. Birinchi bo'lib boshlang.",
    navLogin: "Kirish",
    navRegister: "Ro'yxatdan o'tish",
    navProfile: "Profil",
    navSettings: "Sozlamalar",
    navAdmin: "Admin",
    navLogout: "Chiqish",
    dashboardOverview: "Umumiy",
    settingsTitle: "Akkaunt sozlamalari",
    settingsOverviewTitle: "Akkaunt ma'lumotlari",
    settingsAccountHint: "Profil ma'lumotlaringiz va avataringizni shu yerda yangilang.",
    settingsUsernameLabel: "Foydalanuvchi nomi",
    settingsEmailHint: "Email manzilini hozircha o'zgartirib bo'lmaydi.",
    settingsAvatarLabel: "Profil rasmi",
    settingsChangeAvatarHint: "Ixtiyoriy. Avatarni yangilash uchun rasm yuklang.",
    settingsSaveButton: "O'zgarishlarni saqlash",
    settingsBackToProfile: "Profilga qaytish",
    settingsSaving: "Saqlanmoqda...",
    settingsSaved: "Sozlamalar yangilandi ✓",
    settingsSaveFailed: "O'zgarishlarni saqlab bo'lmadi.",
    settingsPreferencesTitle: "Moslamalar",
    settingsPreferencesHint: "Til darhol yangilanadi va shu brauzerda saqlanib qoladi.",
    settingsLanguageLabel: "Til",
    settingsLanguageEnglish: "English",
    settingsLanguageUzbek: "O'zbek",
    settingsLanguageHint: "Kichik ekranlarda navbar toza ko'rinishi uchun til boshqaruvini shu yerga ko'chirdik.",
    settingsLanguageSaved: "Til yangilandi ✓",
    settingsAccessLabel: "Ruxsat",
    settingsRoleAdmin: "Admin ruxsati",
    settingsRoleMember: "Foydalanuvchi ruxsati",
    settingsUsernameTooShort: "Foydalanuvchi nomi kamida 3 ta belgidan iborat bo'lishi kerak.",
    settingsImageReadFailed: "Tanlangan rasmni o'qib bo'lmadi.",
    settingsDangerTitle: "Xavfli zona",
    settingsDangerHint: "Akkauntni o'chirish profilingizni, natijalaringizni va tarixingizni butunlay olib tashlaydi.",
    settingsDeleteButton: "Akkauntni o'chirish",
    settingsDeleting: "O'chirilmoqda...",
    settingsDeleteConfirm: "Akkauntingizni butunlay o'chirasizmi? Buni qaytarib bo'lmaydi.",
    settingsDeleteFailed: "Akkauntni o'chirib bo'lmadi.",
    quizAuthTitle: "Haqiqiy testni boshlash uchun kiring.",
    quizAuthDesc: "Natijalaringiz va reytingdagi o'rningiz saqlanishi uchun akkaunt kerak bo'ladi.",
    quizAuthLogin: "Kirish",
    quizAuthRegister: "Akkaunt yaratish",
    competitionAuthTitle: "Haqiqiy musobaqa uchun kiring.",
    competitionAuthDesc: "Musobaqa rejimi reytingga saqlanadi, shuning uchun boshlashdan oldin akkaunt kerak.",
    quizLoading: "Savollar yuklanmoqda...",
    quizNoQuestions: "Bu fan uchun hali savollar mavjud emas.",
    scoreSaving: "Natija saqlanmoqda...",
    scoreSaved: "Natija muvaffaqiyatli saqlandi.",
    scoreSaveFailed: "Natijani saqlab bo'lmadi.",
    scoreSaveLogin: "Keyingi natijalarni saqlash uchun qayta kiring.",
    loginTitle: "Yana bir bor xush kelibsiz.",
    loginDesc: "Natijalarni saqlash, reytingda qatnashish va o'sishingizni kuzatish uchun tizimga kiring.",
    registerTitle: "Akkauntingizni yarating.",
    registerDesc: "Bir marta ro'yxatdan o'ting va test tarixingiz, eng yaxshi natijalaringiz hamda musobaqa ballaringizni bir joyda saqlang.",
    authEmailLabel: "Email",
    authPasswordLabel: "Parol",
    authUsernameLabel: "Foydalanuvchi nomi",
    loginSubmit: "Kirish",
    registerSubmit: "Akkaunt yaratish",
    authProcessing: "Yuklanmoqda...",
    loginSwitchText: "Akkauntingiz yo'qmi?",
    loginSwitchLink: "Ro'yxatdan o'ting",
    registerSwitchText: "Akkauntingiz bormi?",
    registerSwitchLink: "Kiring",
    profileMemberSince: "A'zo bo'lgan sana",
    profileStartQuiz: "Mashqni boshlash",
    profileTotalQuizzes: "Yechilgan testlar soni",
    profilePerformanceTab: "Natijalar",
    profileBestResult: "Eng yaxshi natija",
    profileBadgesUnlocked: "Ochilgan badge'lar",
    profileFavoriteMode: "Sevimli rejim",
    profileTrendTitle: "Natijalar dinamikasi",
    profileSubjectFocus: "Fan bo'yicha fokus",
    profileActivityTitle: "Haftalik faollik",
    profileBestScores: "Fanlar bo'yicha eng yaxshi natija",
    profileRecentBadges: "So'nggi olingan badge'lar",
    profileHistory: "Natijalar tarixi",
    profileNoScores: "Hali natijalar yo'q. Tarixni boshlash uchun testni tugating.",
    profileNoBadges: "Hali badge yo'q. Ularni ochish uchun testlarni yakunlang.",
    profileSubjectHeader: "Fan",
    profileModeHeader: "Rejim",
    profileScoreHeader: "Natija",
    profileDateHeader: "Yakunlangan sana",
    profileLevelNewcomer: "Yangi",
    profileLevelBeginner: "Boshlovchi",
    profileLevelIntermediate: "O'rta",
    profileLevelPro: "Pro",
    profileLevelExpert: "Ekspert",
    profileLevelMaster: "Usta",
    profileProgressToNextSingular: "{level} darajaga chiqish uchun yana {remaining} ta test qoldi.",
    profileProgressToNextPlural: "{level} darajaga chiqish uchun yana {remaining} ta test qoldi.",
    profileProgressMax: "Siz eng yuqori darajadasiz — davom eting!",
    profileTopSubjectEmpty: "Hali eng yaxshi natija yo'q",
    profileTopSubjectValue: "Eng yaxshi: {subject} {score}",
    profileTrendSummary: "Oxirgi {count} ta urinish, o'rtacha {average}%.",
    profileTrendBadge: "o'rt. {value}%",
    profileActivitySummary: "Oxirgi 7 kunda {count} kunda faol bo'lgansiz.",
    profileFavoriteModeRuns: "{count} ta urinish",
    profileRunsLabel: "Urinishlar",
    profileBadgeEarnedOn: "Olingan sana: {date}",
    modePractice: "Mashq",
    modeCompetition: "Musobaqa",
    badgeFirstQuiz: "Birinchi zarba",
    badgeFirstQuizDesc: "QuizArena'dagi birinchi testingizni yakunladingiz.",
    badgePracticeStarter: "Mashq boshlovchisi",
    badgePracticeStarterDesc: "Birinchi mashq sessiyangizni tugatdingiz.",
    badgeSpeedRunner: "Tezlik yuguruvchisi",
    badgeSpeedRunnerDesc: "Birinchi marta musobaqa rejimiga kirdingiz.",
    badgeHighScorer: "Yuqori natija",
    badgeHighScorerDesc: "Mashq testida 8 yoki undan yuqori natija oldingiz.",
    badgePerfectTen: "Mukammal o'nlik",
    badgePerfectTenDesc: "Mashq rejimida 10/10 natija oldingiz.",
    badgeSpeedChampion: "Tezlik chempioni",
    badgeSpeedChampionDesc: "Musobaqa rejimida 8 000 yoki undan yuqori ball to'pladingiz.",
    badgeAllRounder: "Har tomonlama kuchli",
    badgeAllRounderDesc: "Uch xil fan bo'yicha mashq testlari ishladingiz.",
    badgeVeteran: "Tajribali",
    badgeVeteranDesc: "Jami 10 ta testni yakunladingiz.",
    adminTitle: "Savol va foydalanuvchi boshqaruvi.",
    adminDesc: "Ikki tildagi savollarni qo'shing, eskilarini olib tashlang va foydalanuvchi faolligini bir paneldan kuzating.",
    adminTotalUsers: "Jami foydalanuvchilar",
    adminQuestionsLive: "Faol savollar",
    adminQuizRunsCount: "Test urinishlari",
    adminSubjectsLive: "Faol fanlar",
    adminGrowthTitle: "Foydalanuvchi o'sishi",
    adminAddQuestion: "Savol qo'shish",
    adminSubjectLabel: "Fan",
    adminQuestionEn: "Savol matni (EN)",
    adminQuestionUz: "Savol matni (UZ)",
    adminOptionsEn: "Variantlar (EN)",
    adminOptionsUz: "Variantlar (UZ)",
    adminCorrectOption: "To'g'ri javob",
    adminSaveQuestion: "Savolni saqlash",
    adminQuestionBank: "Savollar bazasi",
    adminQuestionEnShort: "EN",
    adminQuestionUzShort: "UZ",
    adminActions: "Amallar",
    adminSystemPulse: "Tizim holati",
    adminQuestionMix: "Savollar taqsimoti",
    adminQuestionMixDesc: "Kontentingiz fanlar bo'yicha qanday taqsimlanganini ko'ring.",
    adminQuestionsShort: "Savollar",
    adminGrowthSummaryValue: "{count} ta foydalanuvchi kuzatilmoqda.",
    adminGrowthBadge: "Bu oy +{count}",
    adminPowerUsers: "Eng faol foydalanuvchilar",
    adminPowerUsersSummaryValue: "Faolligi qayd etilgan {count} foydalanuvchi ko'rsatilmoqda.",
    adminPowerUsersMeta: "Eng yaxshi natija {best}",
    adminRecentSignups: "So'nggi ro'yxatdan o'tganlar",
    adminUsersTitle: "Foydalanuvchilar",
    adminUserHeader: "Foydalanuvchi",
    adminTotalQuizzes: "Testlar",
    adminBestScore: "Eng yaxshi natija",
    adminRemoveQuestion: "O'chirish",
    adminSaved: "Savol muvaffaqiyatli saqlandi.",
    adminNoQuestions: "Hali savollar yo'q.",
    adminNoUsers: "Hali foydalanuvchilar yo'q.",
    adminNoRecentUsers: "Hali yangi foydalanuvchilar yo'q.",
    adminLatestSignup: "Oxirgisi: {name}",
    adminAcrossSubjects: "{count} ta fan bo'yicha",
    adminTopSubjectValue: "Eng ko'p: {subject}",
    adminRunsTracked: "Saqlangan natijalar",
  }
};

// Read saved language, default to 'en'
let currentLang = localStorage.getItem('lang') || 'en';

function t(key) {
  return TRANSLATIONS[currentLang][key] || TRANSLATIONS['en'][key] || key;
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang);
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = t(key);
  });
  document.querySelectorAll('[data-language-select]').forEach((select) => {
    select.value = lang;
  });

  if (typeof handleLanguageChange === 'function') {
    handleLanguageChange();
  }
}

function toggleLanguage() {
  setLanguage(currentLang === 'en' ? 'uz' : 'en');
}

// Auto-apply on page load
document.addEventListener('DOMContentLoaded', () => {
  setLanguage(currentLang);
});
